#!/usr/bin/env perl
use strict;
use warnings;

if (defined $ENV{'ROOT_PASSWORD'}) {
    my $new_password = $ENV{'ROOT_PASSWORD'};
    open my $passwd, '| /usr/bin/passwd' or die "failed to open pipe to passwd";
    print $passwd "$new_password\n$new_password";
    close $passwd;
}
