#!/usr/bin/env perl

use strict;
use warnings;

use Concerto::InitScript;

init_script("Computing module dependencies...");

if (system("depmod") == 0) {
    exit 0;
} else {
    print "warning: failed to compute module dependencies\n";
    exit 1;
}
